### ISSUE TITLE
Paubox Email API jar not adding in java build file.

### ISSUE THREAD

**Issue by ranveersingh88** [Paubox/paubox-java#14]
We are using Java Application and using Maven in spring-boot and use Paubox Email API for sending
secure mails. One issue we are facing that when we creating build file (.war or .jar) of java project Paubox jar is not added automatically. We tried also with Plugins provided on "https://github.com/Paubox/paubox-java/blob/master/Paubox_Java/paubox-java/pom.xml"
when we adding jar manually project run on local system but not adding in build file (.war file).

**Comment by eprislac** [comment]
@ranveersingh88 could you provide me with a little more information? Where is the paubox-java jar file in relation to your project? Are you using mvn to install the plugin as a dependency?

**Comment by ranveersingh88** [comment]
We are sending secure emails from the JAVA Application and used in MAVEN.
Yes, We have run the maven install to install plugin as a dependency. but we are not able to load dependency in our build file (war and jar file by command mvn clean build).

**Comment by jacob-castelino** [comment]
@ranveersingh88 are you still facing this issue, what IDE are you using ?

**Comment by jacob-castelino** [comment]
@ranveersingh88 I created a simple client application to use the SDK and packaged it into a jar, the pom.xml needs certain qualifiers to get maven to package all the dependency jars into the application jar. Example pom.xml below, the \<build\> section specifies an assembly plugin which has the details to build the jar with dependencies.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>javasdk-test</artifactId>
    <version>1.0-SNAPSHOT</version>


    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.paubox.PauboxClient</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>Paubox</groupId>
            <artifactId>Paubox</artifactId>
            <version>1.2</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by jacob-castelino** [comment]
not an issue, if the sdk jar is installed in the local repository and the maven-asssembly-plugin is used in the pom.xml as specified in the preceding comment, the packaged jar will contain all the dependency jars
