### ISSUE TITLE
PDF attachment is not opening on client system. 

### ISSUE THREAD

**Issue by ranveersingh88** [Paubox/paubox-java#15]
When we send PDF file by email API, file is sent to the customers within the mail, But not able to open PDF file, It gives an Error "Somthing went wrong".

**Comment by jacob-castelino** [comment]
@ranveersingh88 one thing I can think of that could cause such an error is when you do not specify a proper content type for the attachment, is your contentType for the attachment being set as "application/pdf" ?

**Comment by jacob-castelino** [comment]
@ranveersingh88,

I used a rudimentary PDF file and was able to send myself the email with attachment and was able to view the attachment in the mail application and a PDF reader.

As mentioned in my previous comment, being unable to open a PDF file or any file other than plain text could be one of two reasons as long as one is using a valid and uncorrupted PDF file.

1. the contentType is not correctly specified, for a list of content types for attachments please refer to the following link
https://cloud.google.com/appengine/docs/standard/php/mail/mail-with-headers-attachments

2. the PDF file contents when using the SDK Attachments.setContent() method is not base64 encoded, see code example below.
```java
import java.nio.file.Paths;
import java.util.Base64;
import java.nio.file.Files;

static SendMessageResponse SendMessage()
{
 Message message = new Message();
 Content content = new Content();
 Header header = new Header();
 message.setRecipients(new String[] { "someone@domain.com",
 “someoneelse@domain.com“ });
 header.setFrom("you@yourdomain.com");
 message.setBcc(new String[] { "bcc-recipient@domain.com" });
 header.setSubject("Testing!");
 header.setReplyTo("reply-to@yourdomain.com");
 content.setPlainText("Hello World!");
 message.setHeader(header);
 message.setContent(content);

 // Base64 encode attachment contents and use a valid content type.
 Attachment attachment = new Attachment();
 List<Attachment> listAttachments = new ArrayList<Attachment>();
 attachment.setFileName("testFile.pdf");
 attachment.setContentType("application/pdf");

 byte[] input_file = Files.readAllBytes(Paths.get("test/testFile.pdf"));
 byte[] encodedBytes = Base64.getEncoder().encode(input_file);
 String pdfInBase64 = new String(encodedBytes);

 attachment.setContent(pdfInBase64);
 listAttachments.add(attachment);

 EmailInterface email = new EmailService();
 SendMessageResponse response = email.SendMessage(message);
 return response;
}
```

**Comment by jacob-castelino** [comment]
Please see comment above, also added the same detail to README.md, tested and validated that the API works for PDF attachments.
